spring:
  datasource:
    url: jdbc:mysql://booksdb:3306/booksdb
    username: root
    password: 1234
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: 8080

custom:
  mock: false
  username: admin@somacode.com
  password: 1234
  version: 1.0
  email-enabled: false
  my-secret-token: macaco1234
  access-token-validity: 50000
  refresh-token-validity: 50000
  base-url: 51.75.141.125:8080
  protocol: http